### ISSUE TITLE
exposing secret

### ISSUE THREAD

**Issue by muescha** [PiccoloYu/SaoBear-is-Blog#1]
is this ok to have the secret here visible?

https://github.com/PiccoloYu/SaoBear-is-Blog/blob/522bc4716f9d57bfe80b23b660e435cc63efc165/src/components/Comment/index.js#L10

**Comment by PiccoloYu** [comment]
It's here.  
https://github.com/settings/developers
![image](https://user-images.githubusercontent.com/44945137/71330220-9f6f8800-2566-11ea-8eef-768dd32c181d.png)
![image](https://user-images.githubusercontent.com/44945137/71330228-a72f2c80-2566-11ea-85d2-1c11586bea72.png)

**Comment by PiccoloYu** [comment]
I think you will want to bind your own clientsecret and ClientID.
https://github.com/settings/developers
![image](https://user-images.githubusercontent.com/44945137/71330676-46edba00-2569-11ea-823a-1de2aa450c57.png)
